version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"
#  parameter-store:
#    key: "value"
#    key: "value"
            
phases:
  install:
    commands:
      - mvn initialize
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mvn deploy
  post_build:
    commands:
      - echo Build completed on `date`
#      - mvn deploy
#  post_build:
#    commands:
#artifacts:
#  files:
#    - '**/target/devcase-boot-*.war'
#    - '**/target/devcase-boot-*.jar'
#  discard-paths: yes
#  base-directory: location